input1 = int(input("Enter input number 1:"))
input2 = int(input("Enter input number 2:"))
print("Sum:",input1+input2)
print("Mutiplication:",input1*input2)
print("Subraction:",input1-input2)
print("Division:",input1/input2)
